<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bdi_Rp55</name>
   <tag></tag>
   <elementGuidId>2f322728-de56-46f8-85f2-1d436e473b8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-239']/div/div/div[2]/div/p/ins/span/bdi</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.price > ins > span.woocommerce-Price-amount.amount > bdi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>bdi</value>
      <webElementGuid>c68c809e-ec88-43cf-b7cc-66e1badde975</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rp55</value>
      <webElementGuid>aca9f04a-580c-4a91-aa94-8bfa324d3b16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-239&quot;)/div[@class=&quot;product_infos&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;small-12 large-5 columns&quot;]/div[@class=&quot;summary entry-summary&quot;]/p[@class=&quot;price&quot;]/ins[1]/span[@class=&quot;woocommerce-Price-amount amount&quot;]/bdi[1]</value>
      <webElementGuid>9299153d-eaa4-4e7f-97c4-a2a9d21c4f82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-239']/div/div/div[2]/div/p/ins/span/bdi</value>
      <webElementGuid>6d8e44d8-ed2d-492b-b74f-102b0611db66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp'])[6]/following::bdi[1]</value>
      <webElementGuid>323c7a05-3aa0-4c31-9855-77e895ed255a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belt'])[2]/following::bdi[2]</value>
      <webElementGuid>62aa481e-7569-461d-b9df-4c671adc4fb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belt quantity'])[1]/preceding::bdi[1]</value>
      <webElementGuid>b38fce29-9abb-4e2a-9b7a-dea27f53cb4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/p/ins/span/bdi</value>
      <webElementGuid>e21d3fab-74fe-41db-ad41-a943e0a18ed8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//bdi[(text() = 'Rp55' or . = 'Rp55')]</value>
      <webElementGuid>fb2ef431-d01a-461e-aa3a-c03be822b296</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
