<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_(optional)_order_comments</name>
   <tag></tag>
   <elementGuidId>4d06d560-7267-4d63-92b8-6ddf55b97051</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#order_comments</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='order_comments']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>82a9510c-7738-45af-8e1e-753c6f72ae4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>order_comments</value>
      <webElementGuid>075b090f-7546-4e6e-afaa-133579e402cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text </value>
      <webElementGuid>5a930ecb-8f1f-418e-b798-7aabc6a28e7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>order_comments</value>
      <webElementGuid>53c33929-b1e2-4de0-a0f6-da23f7a4d7d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Notes about your order, e.g. special notes for delivery.</value>
      <webElementGuid>33a344ea-38c1-42b5-890a-32e440c6b5be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>167b8402-9203-48e4-b3f1-dc6468bc4418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>51d1b957-72b6-4b58-9105-1caa17fa4d70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;order_comments&quot;)</value>
      <webElementGuid>fe756dfd-3527-4381-9c32-7982c30703eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='order_comments']</value>
      <webElementGuid>49c1702d-1bc3-432e-88dc-57607cc808c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='order_comments_field']/span/textarea</value>
      <webElementGuid>0cee41c4-ca85-48e4-b980-c19c208652b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>4ff101a5-8520-438d-93ce-a1a348b6b049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'order_comments' and @id = 'order_comments' and @placeholder = 'Notes about your order, e.g. special notes for delivery.']</value>
      <webElementGuid>adf98690-2638-4008-9585-df6adac8a23d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
