<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn login</name>
   <tag></tag>
   <elementGuidId>271785cc-2625-454f-9ccc-56940a6bad20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='um-submit-btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#um-submit-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7c97c192-c1fd-4271-865f-6bdfc561247b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>3f469eba-da89-49de-b821-dccdf121b2ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>97d594b0-70e8-4379-a87b-05d2aa1b61a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>um-button</value>
      <webElementGuid>99d8c5cb-1bbf-4f9d-8151-6eb22f7064c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>um-submit-btn</value>
      <webElementGuid>9ab195a0-1264-448a-9166-b09fe0c83f33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;um-submit-btn&quot;)</value>
      <webElementGuid>5feef926-2295-407f-b7e1-1d957419d967</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='um-submit-btn']</value>
      <webElementGuid>909602c4-77bd-450c-a65a-56766041761d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-313']/div/div/div/form/div[2]/div[3]/input</value>
      <webElementGuid>3a3d03f3-9585-4ced-b2dd-8037d4c9dedc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>1bdae5ea-5bd1-462f-8715-8d361b8a95b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'um-submit-btn']</value>
      <webElementGuid>499814a3-8d55-4db6-8cc5-da0704c059e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
