<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Filters</name>
   <tag></tag>
   <elementGuidId>e85702e2-efef-458c-a966-7db55e0c1d3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/div/div[2]/div/div/header/div/div/div/span[2]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.thehanger-icons-display-list</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>d5251196-b435-4fb4-8723-4be271c3b6d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>thehanger-icons-display-list</value>
      <webElementGuid>fb686ee4-fa1c-460f-9f4d-d7b0bca02018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;small-12 large-9 columns&quot;]/div[@class=&quot;site-main-content-wrapper&quot;]/div[@class=&quot;shop_header_placeholder&quot;]/header[@class=&quot;woocommerce-archive-header&quot;]/div[@class=&quot;woocommerce-archive-header-inside&quot;]/div[@class=&quot;woocommerce-archive-header-tools site-secondary-font site-secondary-color&quot;]/div[@class=&quot;shop-tools&quot;]/span[@class=&quot;shop-display-list&quot;]/i[@class=&quot;thehanger-icons-display-list&quot;]</value>
      <webElementGuid>04ad05d9-acd3-4732-a9d8-4a13f1b7f2f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div[2]/div/div/header/div/div/div/span[2]/i</value>
      <webElementGuid>d3bab320-d717-4d6f-812e-f3db31bf7516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/i</value>
      <webElementGuid>3a99a5cc-15d2-4ece-8cbe-fcbe12dd116e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
