<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>imgalbum</name>
   <tag></tag>
   <elementGuidId>daae0c7e-37f2-4b8f-bfaf-51ac02cc75cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sticky_bottom_anchor']/div/figure/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.wp-post-image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>41a496f1-e4a3-4210-9164-4e84b7dc4bc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>333</value>
      <webElementGuid>96775c75-0f3f-441d-8234-5af04169b8bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>416</value>
      <webElementGuid>7ecf0755-8521-449d-9760-2e2ea40c6382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://kotakoki.wijaysali.my.id/wp-content/uploads/2022/06/IMG-20220606-WA0002.jpg</value>
      <webElementGuid>39ddcc4f-bc8f-4c51-9ec2-fa71b9ed213a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wp-post-image</value>
      <webElementGuid>c542005b-91f7-4315-b8a2-027e43c935d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>98712e29-d377-40db-ad4d-05d61badb9ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>IMG-20220606-WA0002</value>
      <webElementGuid>4a848b3f-a210-41ff-9721-4a5b22d93e5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://kotakoki.wijaysali.my.id/wp-content/uploads/2022/06/IMG-20220606-WA0002.jpg</value>
      <webElementGuid>8e38e177-f5ff-4cba-94c1-e3c9b63d29a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-large_image</name>
      <type>Main</type>
      <value>https://kotakoki.wijaysali.my.id/wp-content/uploads/2022/06/IMG-20220606-WA0002.jpg</value>
      <webElementGuid>5e507d0b-e625-44cf-b76f-bb6a3b24406e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-large_image_width</name>
      <type>Main</type>
      <value>333</value>
      <webElementGuid>3fe5a344-e1e6-4a69-8470-89ca94981488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-large_image_height</name>
      <type>Main</type>
      <value>416</value>
      <webElementGuid>60826b37-f27c-4934-a69a-2c21ebff1f1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://kotakoki.wijaysali.my.id/wp-content/uploads/2022/06/IMG-20220606-WA0002.jpg 333w, https://kotakoki.wijaysali.my.id/wp-content/uploads/2022/06/IMG-20220606-WA0002-330x413.jpg 330w</value>
      <webElementGuid>e4d95b1b-a932-4c0c-9970-4689821267ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 333px) 100vw, 333px</value>
      <webElementGuid>44d1b0ec-88e1-48c7-88f2-89d7d1ad4545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sticky_bottom_anchor&quot;)/div[@class=&quot;woocommerce-product-gallery woocommerce-product-gallery--with-images woocommerce-product-gallery--columns-6 images&quot;]/figure[@class=&quot;woocommerce-product-gallery__wrapper&quot;]/div[@class=&quot;woocommerce-product-gallery__image&quot;]/a[1]/img[@class=&quot;wp-post-image&quot;]</value>
      <webElementGuid>887152c2-31af-4737-b3ec-5422adab2cac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sticky_bottom_anchor']/div/figure/div/a/img</value>
      <webElementGuid>1b26a5b9-c8af-40c7-88fd-9d0621df62ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@title='IMG-20220606-WA0002']</value>
      <webElementGuid>cfb4a5dc-2c36-4dc4-8d45-a6a8110e2851</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//figure/div/a/img</value>
      <webElementGuid>388cd189-e3dd-4eee-8fdc-13c4ef8f02a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://kotakoki.wijaysali.my.id/wp-content/uploads/2022/06/IMG-20220606-WA0002.jpg' and @title = 'IMG-20220606-WA0002']</value>
      <webElementGuid>977d89aa-b6db-4ba6-97e8-5727e4a033a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
