<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_quantity</name>
   <tag></tag>
   <elementGuidId>ea5cb38e-320b-4405-b77b-753a7718147c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='quantity_62ce4800619d6']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#quantity_62ce4800619d6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f4120ea4-e2a9-4cc5-bb8d-7c8e87b349e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>67586d62-3106-4590-9868-b3211f677725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>quantity_62ce4800619d6</value>
      <webElementGuid>4b25de02-28e6-4ad4-b174-df0d1001f0ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text qty text</value>
      <webElementGuid>256bdd1a-1f28-427c-8ce1-76542281b45e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>046cdaa0-f88e-4af4-aa78-c2896f52f83f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>67ecdfcd-20cb-4e56-8b88-3b0dd2c3598d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>quantity</value>
      <webElementGuid>95b837b3-319f-4ea4-8641-fe8557c95787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>4c17913a-f8a5-4fc8-bb8e-688c9c1b4236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Qty</value>
      <webElementGuid>523cb598-a74e-4d40-84d4-0ec232bbf705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>85927d2c-1ea9-491b-8fff-0286f222eef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>fadcdbd9-70d2-414c-a6b2-9f759e568263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7616a2e0-150c-4b03-9718-68c113e62eda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;quantity_62ce4800619d6&quot;)</value>
      <webElementGuid>38a32229-a45f-4837-a8f7-0790587fb760</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='quantity_62ce4800619d6']</value>
      <webElementGuid>e03eeccb-826b-48b4-b813-30c6152127d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-17']/div/div/div[2]/div/form/div/div/input</value>
      <webElementGuid>1bfce12b-a6c1-45cf-bc37-46d7c73bb14b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>a0e1574c-da10-4ae0-96e4-1dea3cd26503</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'quantity_62ce4800619d6' and @name = 'quantity' and @title = 'Qty']</value>
      <webElementGuid>00a1f728-e9e3-4eae-89f4-cb1e65f93622</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
