<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Description</name>
   <tag></tag>
   <elementGuidId>031f0ca2-1017-4120-864f-aa4f630627c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='tab-title-description']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tab-title-description > #tab-title-description</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>76a8e527-d240-4450-9a86-c4f11ea27e72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>accordion-title description_tab</value>
      <webElementGuid>34e23d88-3034-4ba8-871a-9eeee46f0043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#tab-description</value>
      <webElementGuid>93fb15a6-c36d-456f-be05-ed21decec109</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>tab-description</value>
      <webElementGuid>f2214964-2d23-47f3-aa83-6238b8601a8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>179aea9a-8c7c-4aab-8c88-aaddb7b3a9e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tab-title-description</value>
      <webElementGuid>706e403f-0c8b-4a6d-b1c3-f477ae6e62f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a351a065-6f44-4284-8239-d6cc32acb95c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>69b22809-27c0-4dbf-8800-d5703eb4623c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
					Description				</value>
      <webElementGuid>6bf12477-ad78-4639-aad0-ab78d6cc7a8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-26&quot;)/div[@class=&quot;product_infos&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;small-12 large-5 columns&quot;]/div[@class=&quot;summary entry-summary&quot;]/div[@class=&quot;woocommerce-gb_accordion&quot;]/ul[@class=&quot;accordion&quot;]/li[@id=&quot;tab-title-description&quot;]/a[@id=&quot;tab-title-description&quot;]</value>
      <webElementGuid>91c4e215-6092-4b52-8076-bbbf98a2eb8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='tab-title-description']</value>
      <webElementGuid>02bf551e-5c40-4b7f-a8fc-dc123389b50a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='tab-title-description']/a</value>
      <webElementGuid>082caf77-62e9-4367-9f0c-77d8d1e83c6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Description')]</value>
      <webElementGuid>44fda60f-7f4a-4064-aab5-fb73f1b45677</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Share'])[1]/following::a[4]</value>
      <webElementGuid>1740fb56-ad58-4c33-b576-532a738b5bd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to cart'])[2]/following::a[4]</value>
      <webElementGuid>83e76201-12e6-4cff-b3c8-3f20adabbd09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional information'])[1]/preceding::a[1]</value>
      <webElementGuid>6068fb24-27f4-4bc0-b97d-dc784639f104</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='color'])[1]/preceding::a[2]</value>
      <webElementGuid>64dce0a5-9768-452f-acca-917938ca5623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Description']/parent::*</value>
      <webElementGuid>f5d60810-6ca3-4a0d-82b7-4537cbab697b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#tab-description')]</value>
      <webElementGuid>48319f64-b91e-4cdb-8213-6c45297f75d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/ul/li/a</value>
      <webElementGuid>a12da05d-dbce-4d86-82bf-c675ddbdfd26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#tab-description' and @id = 'tab-title-description' and (text() = '
					Description				' or . = '
					Description				')]</value>
      <webElementGuid>c1e0edf1-d71d-401c-827e-29813babea1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
