<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Buy on the WordPress swag store</name>
   <tag></tag>
   <elementGuidId>7f0839fc-5b32-4278-af95-99f1077b3f53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-28']/div/div/div[2]/div/div[2]/p/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.single_add_to_cart_button.button.alt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e0fc21b5-06b6-4552-8c78-49d1233dcf39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://mercantile.wordpress.org/product/wordpress-pennant/</value>
      <webElementGuid>0f800dcf-57aa-45db-872e-ac094ad79310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>ffd9650d-0ee1-4f28-af4c-b43bbcaa9347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>nofollow</value>
      <webElementGuid>82dda1d7-ed9d-4484-a61e-400a94f84c3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>single_add_to_cart_button button alt</value>
      <webElementGuid>671e5973-cdf0-48ad-9364-e739135f1876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Buy on the WordPress swag store!</value>
      <webElementGuid>8d4f4f7c-42cc-4de6-81ad-1e0e8396db8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-28&quot;)/div[@class=&quot;product_infos&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;small-12 large-5 columns&quot;]/div[@class=&quot;summary entry-summary&quot;]/div[@class=&quot;add_to_cart_wrapper&quot;]/p[@class=&quot;cart&quot;]/a[@class=&quot;single_add_to_cart_button button alt&quot;]</value>
      <webElementGuid>a6e4bb28-87f8-4e9c-a524-4be7e0f325b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-28']/div/div/div[2]/div/div[2]/p/a</value>
      <webElementGuid>07f2aa98-aed9-4372-8a98-4b05f084735f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Buy on the WordPress swag store!')]</value>
      <webElementGuid>9d21ca34-d988-40df-98ca-f44d4b2f3af3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp'])[7]/following::a[1]</value>
      <webElementGuid>5849ae00-86ec-4db8-b969-eab222ee2932</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='External Product'])[2]/following::a[1]</value>
      <webElementGuid>a72c567d-ae08-448a-a468-8dde22f8b514</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Share'])[1]/preceding::a[1]</value>
      <webElementGuid>fa192b1b-aacf-4eb1-9520-0c345ab5edaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/preceding::a[4]</value>
      <webElementGuid>5586c408-0ac7-492b-a7f0-220a15446bc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://mercantile.wordpress.org/product/wordpress-pennant/')])[2]</value>
      <webElementGuid>f402b352-3347-4e4c-8842-1c3e5b82a34b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p/a</value>
      <webElementGuid>d715b723-201f-47d1-a40a-052ce6c04f83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://mercantile.wordpress.org/product/wordpress-pennant/' and (text() = 'Buy on the WordPress swag store!' or . = 'Buy on the WordPress swag store!')]</value>
      <webElementGuid>70833c80-6db5-4325-88e8-4f847028a208</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
