<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Single 1</name>
   <tag></tag>
   <elementGuidId>5146a227-ec2e-4f0c-8926-c5b293768d65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-54']/div/div/div/section/table/tbody/tr/td[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.woocommerce-MyAccount-downloads-file.button.alt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c72e62d7-c6a3-4195-8c38-87e720baa667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://kotakoki.wijaysali.my.id/?download_file=17&amp;order=wc_order_HwSVRxqgcJ9sK&amp;uid=f42ff5e392ac2c8e15b959532cdf489331a4a4c4c89ec3fb72cf35211de73fe3&amp;key=83aac240-d70e-4456-9926-26b7f9287f43</value>
      <webElementGuid>453d9b02-155f-42e4-ad5f-acbd8390b0e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-MyAccount-downloads-file button alt</value>
      <webElementGuid>911626ce-e6c5-4408-ae19-a4a2be9cfce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Single 1</value>
      <webElementGuid>e9291894-efd8-4c68-abcb-664dcce4d6d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-54&quot;)/div[@class=&quot;entry-content&quot;]/div[@class=&quot;woocommerce&quot;]/div[@class=&quot;woocommerce-order&quot;]/section[@class=&quot;woocommerce-order-downloads&quot;]/table[@class=&quot;woocommerce-table woocommerce-table--order-downloads shop_table shop_table_responsive order_details&quot;]/tbody[1]/tr[1]/td[@class=&quot;download-file&quot;]/a[@class=&quot;woocommerce-MyAccount-downloads-file button alt&quot;]</value>
      <webElementGuid>f1a5cd3d-9c99-4fc1-a8a4-7472c66e9557</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-54']/div/div/div/section/table/tbody/tr/td[4]/a</value>
      <webElementGuid>727f2837-820e-4198-8db3-fdc4ea3a9bbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Single 1')]</value>
      <webElementGuid>e31519e5-e740-4b31-8423-db60a3153e2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='July 14, 2022'])[1]/following::a[1]</value>
      <webElementGuid>f7158b5e-aaad-479b-a513-869ee3058918</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Album'])[1]/following::a[1]</value>
      <webElementGuid>9e69c92e-f6cd-45d5-86bf-42d753522971</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Album'])[2]/preceding::a[1]</value>
      <webElementGuid>c881729c-e188-4829-98bb-df1dbc606bff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='July 14, 2022'])[2]/preceding::a[2]</value>
      <webElementGuid>b722c5fe-875f-4f6f-834b-0dadfc61254e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Single 1']/parent::*</value>
      <webElementGuid>5cd3c2ad-27c8-42bd-b6d7-d24903054116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://kotakoki.wijaysali.my.id/?download_file=17&amp;order=wc_order_HwSVRxqgcJ9sK&amp;uid=f42ff5e392ac2c8e15b959532cdf489331a4a4c4c89ec3fb72cf35211de73fe3&amp;key=83aac240-d70e-4456-9926-26b7f9287f43')]</value>
      <webElementGuid>9b72d4c2-90f1-4fe9-9db7-d3731b66f10e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/a</value>
      <webElementGuid>bf590c83-5608-47bf-9b74-e943bff11d9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://kotakoki.wijaysali.my.id/?download_file=17&amp;order=wc_order_HwSVRxqgcJ9sK&amp;uid=f42ff5e392ac2c8e15b959532cdf489331a4a4c4c89ec3fb72cf35211de73fe3&amp;key=83aac240-d70e-4456-9926-26b7f9287f43' and (text() = 'Single 1' or . = 'Single 1')]</value>
      <webElementGuid>5bcaad72-f38d-4948-8790-05fc603f3229</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
