<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Single 2</name>
   <tag></tag>
   <elementGuidId>e4c6c2d5-27a7-451e-9095-cfce732928ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-54']/div/div/div/section/table/tbody/tr[2]/td[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6878efde-10f9-42c1-88b3-7fa001658af8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://kotakoki.wijaysali.my.id/?download_file=17&amp;order=wc_order_HwSVRxqgcJ9sK&amp;uid=f42ff5e392ac2c8e15b959532cdf489331a4a4c4c89ec3fb72cf35211de73fe3&amp;key=67ce89a5-ed8e-481c-b8ba-602374231f36</value>
      <webElementGuid>e39560fc-a448-4ac3-a1f0-d783aff1e35e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-MyAccount-downloads-file button alt</value>
      <webElementGuid>42aba149-4ad8-4adf-a837-fc9ac923e04c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Single 2</value>
      <webElementGuid>b7c16b62-33c3-4922-b007-750ed27c0b1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-54&quot;)/div[@class=&quot;entry-content&quot;]/div[@class=&quot;woocommerce&quot;]/div[@class=&quot;woocommerce-order&quot;]/section[@class=&quot;woocommerce-order-downloads&quot;]/table[@class=&quot;woocommerce-table woocommerce-table--order-downloads shop_table shop_table_responsive order_details&quot;]/tbody[1]/tr[2]/td[@class=&quot;download-file&quot;]/a[@class=&quot;woocommerce-MyAccount-downloads-file button alt&quot;]</value>
      <webElementGuid>76dec5b2-258d-424b-bb56-963690acd7b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-54']/div/div/div/section/table/tbody/tr[2]/td[4]/a</value>
      <webElementGuid>64623e88-9dc0-4142-b605-0350c42a52d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Single 2')]</value>
      <webElementGuid>d7f270da-7e6a-4da6-a89e-223c2f095d13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='July 14, 2022'])[2]/following::a[1]</value>
      <webElementGuid>237f988e-971b-4dd0-8312-69e11713a6c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Album'])[2]/following::a[1]</value>
      <webElementGuid>f86ceb20-ac28-46ed-b5e2-3d1960ef8af1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order details'])[1]/preceding::a[1]</value>
      <webElementGuid>8827d2cc-fe61-4c35-8412-92f313bda714</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product'])[2]/preceding::a[1]</value>
      <webElementGuid>cabc7c07-3686-46f2-a605-176c00f5c55a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Single 2']/parent::*</value>
      <webElementGuid>16d77511-27ee-4148-8bc6-e34cdd914239</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://kotakoki.wijaysali.my.id/?download_file=17&amp;order=wc_order_HwSVRxqgcJ9sK&amp;uid=f42ff5e392ac2c8e15b959532cdf489331a4a4c4c89ec3fb72cf35211de73fe3&amp;key=67ce89a5-ed8e-481c-b8ba-602374231f36')]</value>
      <webElementGuid>d9cbc208-9649-412f-bd3c-6111ca9557fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[4]/a</value>
      <webElementGuid>75394792-b96d-4886-8ce1-ae981d4cfe18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://kotakoki.wijaysali.my.id/?download_file=17&amp;order=wc_order_HwSVRxqgcJ9sK&amp;uid=f42ff5e392ac2c8e15b959532cdf489331a4a4c4c89ec3fb72cf35211de73fe3&amp;key=67ce89a5-ed8e-481c-b8ba-602374231f36' and (text() = 'Single 2' or . = 'Single 2')]</value>
      <webElementGuid>a2353612-b3be-4ed5-8b13-0b3622a0faf2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
