<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>comments</name>
   <tag></tag>
   <elementGuidId>aed68965-cd8f-4bdd-8caf-0b23b555a54b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='order_comments']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#order_comments</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>f104cdcb-7d3f-458f-8667-74606d0bb874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>order_comments</value>
      <webElementGuid>e3a1b300-ae0a-46a7-b622-cdec499c093e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text </value>
      <webElementGuid>0c84216d-a453-4a68-a251-eb42af095471</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>order_comments</value>
      <webElementGuid>f8a2b1ec-174c-4c20-9de8-3fada227d535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Notes about your order, e.g. special notes for delivery.</value>
      <webElementGuid>15a92c9b-cdfd-41a3-b4cf-82d915d10c53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>15f9c623-95a8-45a3-a072-c167f1cb324e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>895be435-4ad2-4380-b1d9-a06bbb54042d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;order_comments&quot;)</value>
      <webElementGuid>be35a6c7-2b25-49aa-8cdb-3777b3235a65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='order_comments']</value>
      <webElementGuid>23b3bd1c-139e-473b-b7d4-78716cb13d17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='order_comments_field']/span/textarea</value>
      <webElementGuid>9759d0e6-deef-4d24-8c55-ff8d9a390175</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>f88cc0bc-ebb1-4b3b-8cc8-8b92ea128ad2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'order_comments' and @id = 'order_comments' and @placeholder = 'Notes about your order, e.g. special notes for delivery.']</value>
      <webElementGuid>3779e844-7933-49e2-8b42-f43b615691a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
