<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>payment_method3</name>
   <tag></tag>
   <elementGuidId>74c7d4cc-b397-45d7-a897-39b11b90e8bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='payment_method_xendit_briva']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#payment_method_xendit_briva</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1dab396c-1111-4699-9994-b9f5087e80e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payment_method_xendit_briva</value>
      <webElementGuid>afea44ad-e5bf-4bb6-8bb1-079a8163960d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>653a8df6-df75-4e3f-aa99-ca86b7d6b3e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-radio</value>
      <webElementGuid>174a2e08-edb2-4e40-b091-f73e91193b69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payment_method</value>
      <webElementGuid>ee08c3a5-c7b2-473d-9fb6-25056a2357bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>xendit_briva</value>
      <webElementGuid>3941fb9c-8def-4ae5-aed5-ca0a754f42f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment_method_xendit_briva&quot;)</value>
      <webElementGuid>7e808ba5-c32f-4605-ba72-9921deea409f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='payment_method_xendit_briva']</value>
      <webElementGuid>c396efc4-2d9c-45ce-baf6-347c02c1b4d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment']/ul/li[3]/input</value>
      <webElementGuid>9058151f-0c81-4bf3-b75a-95ad9301b3f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/input</value>
      <webElementGuid>e8471c67-6bf9-4971-aed3-5a2379cdc07f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'payment_method_xendit_briva' and @type = 'radio' and @name = 'payment_method']</value>
      <webElementGuid>6a16c0fc-8f3b-4741-9f12-b3e2594a074f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
