<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Confirm</name>
   <tag></tag>
   <elementGuidId>a903532f-fab9-4233-8328-9421b6d7dade</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='confirm_user_password-297']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#confirm_user_password-297</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7daca24e-89b8-41ca-aefe-85ea9b51fc11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>um-form-field valid um-validate-not-matched</value>
      <webElementGuid>406c85ab-e3ec-42ec-8cd5-d39623620d40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>34b6ac9b-3782-4f14-8db0-f1606bc600d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>confirm_user_password-297</value>
      <webElementGuid>9de44428-08d8-42fe-b512-f9871a9ff7b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirm_user_password-297</value>
      <webElementGuid>60cc6f16-c30a-4309-a9e7-f65665413d8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Confirm Password</value>
      <webElementGuid>c1c4d5e4-484a-46bb-9d96-c5152ad7b7ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>confirm_user_password</value>
      <webElementGuid>0e030737-946c-4414-95d0-4011a6ad331d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirm_user_password-297&quot;)</value>
      <webElementGuid>75541c73-a75b-4ff1-b7ca-551852078cb8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='confirm_user_password-297']</value>
      <webElementGuid>2e9737cc-901a-4bae-b954-8b82a64a7948</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='um_field_297_confirm_user_password']/div[2]/input</value>
      <webElementGuid>2d237ef0-e98c-4236-8cad-011413b19150</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/input</value>
      <webElementGuid>3ec17ef8-37b1-4dfa-aaa1-96492e9dc5ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'confirm_user_password-297' and @id = 'confirm_user_password-297' and @placeholder = 'Confirm Password']</value>
      <webElementGuid>44286cec-dfe3-444b-8211-87646b40b372</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
